# Generated by Django 4.2.14 on 2024-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('desc', models.TextField(max_length=800)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
